/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as TestesRouteImport } from './routes/testes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoComprasRouteImport } from './routes/historico-compras'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ContasAReceberRouteImport } from './routes/contas-a-receber'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const TestesRoute = TestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoComprasRoute = HistoricoComprasRouteImport.update({
  id: '/historico-compras',
  path: '/historico-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasAReceberRoute = ContasAReceberRouteImport.update({
  id: '/contas-a-receber',
  path: '/contas-a-receber',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/estoque': typeof EstoqueRoute
  '/historico-compras': typeof HistoricoComprasRoute
  '/login': typeof LoginRoute
  '/testes': typeof TestesRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/estoque': typeof EstoqueRoute
  '/historico-compras': typeof HistoricoComprasRoute
  '/login': typeof LoginRoute
  '/testes': typeof TestesRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/estoque': typeof EstoqueRoute
  '/historico-compras': typeof HistoricoComprasRoute
  '/login': typeof LoginRoute
  '/testes': typeof TestesRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/compras'
    | '/contas-a-receber'
    | '/estoque'
    | '/historico-compras'
    | '/login'
    | '/testes'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/compras'
    | '/contas-a-receber'
    | '/estoque'
    | '/historico-compras'
    | '/login'
    | '/testes'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/compras'
    | '/contas-a-receber'
    | '/estoque'
    | '/historico-compras'
    | '/login'
    | '/testes'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  ContasAReceberRoute: typeof ContasAReceberRoute
  EstoqueRoute: typeof EstoqueRoute
  HistoricoComprasRoute: typeof HistoricoComprasRoute
  LoginRoute: typeof LoginRoute
  TestesRoute: typeof TestesRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testes': {
      id: '/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof TestesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-compras': {
      id: '/historico-compras'
      path: '/historico-compras'
      fullPath: '/historico-compras'
      preLoaderRoute: typeof HistoricoComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-a-receber': {
      id: '/contas-a-receber'
      path: '/contas-a-receber'
      fullPath: '/contas-a-receber'
      preLoaderRoute: typeof ContasAReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  ContasAReceberRoute: ContasAReceberRoute,
  EstoqueRoute: EstoqueRoute,
  HistoricoComprasRoute: HistoricoComprasRoute,
  LoginRoute: LoginRoute,
  TestesRoute: TestesRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
